package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"
)

var agentFormat string

var agentCmd = &cobra.Command{
	Use:   "agent",
	Short: "Show help for AI agents",
	Long: `Output a structured instruction tree meant for AI agents (LLMs).

This command provides comprehensive information that an AI assistant can use to
help users work with lyt effectively. Use this when an AI agent needs to
understand lyt's capabilities, commands, and workflows.

Output formats:
- markdown (default): Human-readable with clear headings
- json: Machine-parseable structure`,
	RunE: runHelpAgent,
}

func runHelpAgent(cmd *cobra.Command, args []string) error {
	agentHelp := AgentHelp{
		Version:     "1.0.0",
		Description: "lyt - a minimal static site generator",
		Commands: []AgentCommand{
			{
				Name:        "build",
				Description: "Build the static site from content and templates",
				Usage:       "lyt build [flags]",
				Flags: []AgentFlag{
					{Name: "-o, --output", Description: "Output directory (default: ./dist)"},
					{Name: "-f, --force", Description: "Force rebuild even when no changes detected"},
					{Name: "-v, --verbose", Description: "Verbose output"},
				},
				Example: "lyt build -o ./build",
			},
			{
				Name:        "init",
				Description: "Initialize a new lyt project with default content and templates",
				Usage:       "lyt init [flags]",
				Flags: []AgentFlag{
					{Name: "-f, --force", Description: "Force initialization even if directory is not empty"},
					{Name: "-v, --verbose", Description: "Verbose output"},
				},
				Example: "mkdir my-blog && cd my-blog && lyt init",
			},
			{
				Name:        "serve",
				Description: "Start the development server with live reload",
				Usage:       "lyt serve [flags]",
				Flags: []AgentFlag{
					{Name: "-p, --port", Description: "Port to listen on (default: 8080)"},
					{Name: "-v, --verbose", Description: "Verbose output"},
				},
				Example: "lyt serve -p 3000",
			},
			{
				Name:        "agent",
				Description: "Show this help information for AI agents",
				Usage:       "lyt help agent [format]",
				Flags:       []AgentFlag{},
				Example:     "lyt help agent json",
			},
			{
				Name:        "validate",
				Description: "Validate content files against schema (content/schema.yaml)",
				Usage:       "lyt validate [flags]",
				Flags: []AgentFlag{
					{Name: "-s, --strict", Description: "Treat warnings as errors"},
					{Name: "-f, --fix", Description: "Attempt to fix common issues"},
				},
				Example: "lyt validate",
			},
		},
		ProjectStructure: AgentProjectStructure{
			Root: map[string]string{
				"content/":   "YAML content files (pages and blog posts)",
				"templates/": "Templates and stylesheets",
				"public/":    "Static assets (images, fonts, etc.)",
				"dist/":      "Built output (generated by build command)",
			},
			Content: map[string]string{
				"content/pages/":      "Page content (YAML files)",
				"content/blog/":       "Blog post content (YAML files)",
				"content/config/":     "Site configuration",
				"content/tokens.yaml": "Design tokens (colors, typography, spacing)",
			},
		},
		ContentSchema: AgentContentSchema{
			Frontmatter: []string{"title", "slug", "description", "date", "tags", "draft", "agent"},
			SectionTypes: []string{
				"hero: Hero section with title, subtitle, body, and buttons",
				"features: Feature grid with cards",
				"default: Standard content section",
				"cta: Call-to-action banner",
				"pull-quote: Blockquote with attribution",
				"citation: Reference/citation block",
				"warning: Warning notice box",
				"callout: Informational callout",
				"code-example: Syntax-highlighted code block",
			},
			AgentSectionTypes: []string{
				"default: Text content with title and body",
				"cli: CLI command reference",
				"schema: Code/schema examples",
				"example: Usage examples",
				"link: Navigation links",
			},
		},
		Workflows: []AgentWorkflow{
			{
				Name:        "Create new project",
				Steps:       []string{"mkdir my-project && cd my-project", "lyt init", "lyt build", "lyt serve"},
				Description: "Initialize a new project and start development",
			},
			{
				Name:        "Validate content",
				Steps:       []string{"lyt validate", "Review any errors", "Fix content/schema.yaml issues"},
				Description: "Check content files for schema compliance before building",
			},
			{
				Name:        "Build with validation",
				Steps:       []string{"lyt build --validate", "Review dist/ output"},
				Description: "Build site and validate content in one step",
			},
			{
				Name:        "Add new page",
				Steps:       []string{"Create content/pages/pagename.yaml", "lyt build", "Check dist/pagename.html"},
				Description: "Add a new page to the site",
			},
			{
				Name:        "Add new blog post",
				Steps:       []string{"Create content/blog/post-title.yaml", "lyt build", "Check dist/blog/post-title/index.html"},
				Description: "Add a new blog post",
			},
			{
				Name:        "Customize design",
				Steps:       []string{"Edit content/tokens.yaml", "lyt build", "Review dist/tokens.css"},
				Description: "Modify colors, typography, and spacing via design tokens",
			},
			{
				Name:        "Deploy site",
				Steps:       []string{"lyt build --validate -o ./dist", "Deploy dist/ to hosting provider"},
				Description: "Build, validate, and deploy to production",
			},
		},
		HostingProviders: []AgentHosting{
			{Name: "Netlify", BuildCommand: "lyt build", OutputDir: "dist", Notes: "Connect git repo, automatic deploys"},
			{Name: "Vercel", BuildCommand: "lyt build", OutputDir: "dist", Notes: "Connect git repo, automatic deploys"},
			{Name: "Cloudflare Pages", BuildCommand: "lyt build", OutputDir: "dist", Notes: "Connect git repo, automatic deploys"},
			{Name: "GitHub Pages", BuildCommand: "lyt build -o ./dist", OutputDir: "dist", Notes: "Use GitHub Actions"},
			{Name: "rsync/VPS", BuildCommand: "lyt build -o ./dist", OutputDir: "dist", Notes: "rsync dist/ to server"},
		},
	}

	switch agentFormat {
	case "json":
		output, err := json.MarshalIndent(agentHelp, "", "  ")
		if err != nil {
			return fmt.Errorf("marshal json: %w", err)
		}
		fmt.Println(string(output))
	default:
		// Markdown output
		fmt.Println("# lyt Help for AI Agents")
		fmt.Println()
		fmt.Println("## Overview")
		fmt.Printf("**Version:** %s\n\n", agentHelp.Version)
		fmt.Println(agentHelp.Description)
		fmt.Println()
		fmt.Println("## Commands")
		fmt.Println()

		for _, cmd := range agentHelp.Commands {
			fmt.Printf("### %s\n\n", cmd.Name)
			fmt.Printf("**Description:** %s\n\n", cmd.Description)
			fmt.Printf("**Usage:** `%s`\n\n", cmd.Usage)
			if len(cmd.Flags) > 0 {
				fmt.Println("**Flags:**")
				for _, flag := range cmd.Flags {
					fmt.Printf("  - %s\n", flag.Description)
				}
				fmt.Println()
			}
			fmt.Printf("**Example:** `%s`\n\n", cmd.Example)
		}

		fmt.Println("## Project Structure")
		fmt.Println()
		fmt.Println("```")
		fmt.Println("project-root/")
		for dir, desc := range agentHelp.ProjectStructure.Root {
			fmt.Printf("├── %s  (%s)\n", dir, desc)
		}
		fmt.Println("│")
		for dir, desc := range agentHelp.ProjectStructure.Content {
			fmt.Printf("├── %s  (%s)\n", dir, desc)
		}
		fmt.Println("```")
		fmt.Println()

		fmt.Println("## Content Schema")
		fmt.Println()
		fmt.Println("### Frontmatter Fields")
		fmt.Println("- " + frontmatterFields(agentHelp.ContentSchema.Frontmatter))
		fmt.Println()
		fmt.Println("### Section Types")
		for _, st := range agentHelp.ContentSchema.SectionTypes {
			fmt.Printf("- %s\n", st)
		}
		fmt.Println()

		fmt.Println("### Agent Section Types")
		for _, st := range agentHelp.ContentSchema.AgentSectionTypes {
			fmt.Printf("- %s\n", st)
		}
		fmt.Println()

		fmt.Println("## Common Workflows")
		fmt.Println()
		for _, wf := range agentHelp.Workflows {
			fmt.Printf("### %s\n\n", wf.Name)
			fmt.Println(wf.Description)
			fmt.Println()
			fmt.Println("Steps:")
			for i, step := range wf.Steps {
				fmt.Printf("%d. `%s`\n", i+1, step)
			}
			fmt.Println()
		}

		fmt.Println("## Deployment")
		fmt.Println()
		fmt.Println("| Provider | Build Command | Output | Notes |")
		fmt.Println("|----------|--------------|--------|-------|")
		for _, hp := range agentHelp.HostingProviders {
			fmt.Printf("| %s | `%s` | %s | %s |\n",
				hp.Name, hp.BuildCommand, hp.OutputDir, hp.Notes)
		}
		fmt.Println()
		fmt.Println("## Tips for AI Assistants")
		fmt.Println()
		fmt.Println("1. Always run `lyt init` first when creating a new project")
		fmt.Println("2. Use `lyt serve` for live preview during development")
		fmt.Println("3. Design tokens in content/tokens.yaml control the visual theme")
		fmt.Println("4. Section types are composable - mix and match in YAML")
		fmt.Println("5. The build output is static HTML/CSS - no JavaScript required")
		fmt.Println("6. Use `--verbose` flag for detailed output during troubleshooting")
		fmt.Println("7. Use `lyt validate` or `lyt build --validate` to check schema compliance")
		fmt.Println("8. Schema is defined in content/schema.yaml - validate before building")
	}

	return nil
}

func frontmatterFields(fields []string) string {
	result := ""
	for i, f := range fields {
		if i > 0 {
			result += ", "
		}
		result += f
	}
	return result
}

// AgentHelp represents the structured help for AI agents
type AgentHelp struct {
	Version          string                `json:"version"`
	Description      string                `json:"description"`
	Commands         []AgentCommand        `json:"commands"`
	ProjectStructure AgentProjectStructure `json:"project_structure"`
	ContentSchema    AgentContentSchema    `json:"content_schema"`
	Workflows        []AgentWorkflow       `json:"workflows"`
	HostingProviders []AgentHosting        `json:"hosting_providers"`
}

type AgentCommand struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Usage       string      `json:"usage"`
	Flags       []AgentFlag `json:"flags,omitempty"`
	Example     string      `json:"example"`
}

type AgentFlag struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type AgentProjectStructure struct {
	Root    map[string]string `json:"root"`
	Content map[string]string `json:"content"`
}

type AgentContentSchema struct {
	Frontmatter       []string `json:"frontmatter"`
	SectionTypes      []string `json:"section_types"`
	AgentSectionTypes []string `json:"agent_section_types"`
}

type AgentWorkflow struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Steps       []string `json:"steps"`
}

type AgentHosting struct {
	Name         string `json:"name"`
	BuildCommand string `json:"build_command"`
	OutputDir    string `json:"output_dir"`
	Notes        string `json:"notes"`
}

func init() {
	rootCmd.AddCommand(agentCmd)
	agentCmd.Flags().StringVar(&agentFormat, "format", "markdown", "Output format: markdown, json")
}
